### ISSUE TITLE
getting invalid auto_int value: 'TelegramBot' error

### ISSUE THREAD

**Issue by teddybear757** [sanjit-sinha/Tg-MediaInfoBot#20]

**Comment by sanjit-sinha** [comment]
Not enough information provided

**Comment by teddybear757** [comment]
> Not enough information provided

bro when i try to deploy it on doprax, i get this error
`/usr/bin/python3: No module named TelegramBot`
Will u help me to fix this?

**Comment by sanjit-sinha** [comment]
No idea about doprax. This is deployable is any normal VPS using docker or without docker.

**Comment by teddybear757** [comment]
> Ref

ok bro i managed to deploy it and bot started, but i got this another error, 
```
` [16-Apr-23 11:04:54 - INFO] - apscheduler.scheduler - Adding job tentatively -- it will be properly scheduled when the scheduler starts

[16-Apr-23 11:04:54 - INFO] - apscheduler.scheduler - Added job "clear_download" to job store "default"

[16-Apr-23 11:04:54 - INFO] - apscheduler.scheduler - Scheduler started

[16-Apr-23 11:04:54 - INFO] - TelegramBot - initiating the client....

[16-Apr-23 11:04:54 - INFO] - __main__ - client successfully initiated...

[16-Apr-23 11:22:05 - ERROR] - TelegramBot.plugins.mediainfo - [Errno 2] No such file or directory

[16-Apr-23 11:22:05 - ERROR] - pyrogram.dispatcher - Telegram says: [400 MESSAGE_NOT_MODIFIED] - The message was not modified because you tried to edit it using the same content (caused by "messages.EditMessage")

Traceback (most recent call last):

File "/app/ok/TelegramBot/plugins/mediainfo.py", line 48, in gdrive_mediainfo

mediainfo = await async_subprocess(f"mediainfo {download_path}")

File "/app/ok/TelegramBot/helpers/functions.py", line 137, in async_subprocess

process = await asyncio.create_subprocess_exec(

File "/usr/lib/python3.9/asyncio/subprocess.py", line 236, in create_subprocess_exec

transport, protocol = await loop.subprocess_exec(

File "uvloop/loop.pyx", line 2820, in subprocess_exec

File "uvloop/loop.pyx", line 2778, in __subprocess_run

File "uvloop/handles/process.pyx", line 588, in uvloop.loop.UVProcessTransport.new

File "uvloop/handles/process.pyx", line 104, in uvloop.loop.UVProcess._init

FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/dist-packages/pyrogram/session/session.py", line 361, in invoke

return await self.send(query, timeout=timeout)

File "/usr/local/lib/python3.9/dist-packages/pyrogram/session/session.py", line 326, in send

raise TimeoutError

TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker

await handler.callback(self.client, *args)

File "/app/ok/TelegramBot/plugins/mediainfo.py", line 306, in mediainfo

return await gdrive_mediainfo(message, url, isRaw)

File "/app/ok/TelegramBot/plugins/mediainfo.py", line 99, in gdrive_mediainfo

return await reply_msg.edit(

File "/usr/local/lib/python3.9/dist-packages/pyrogram/types/messages_and_media/message.py", line 2778, in edit_text

return await self._client.edit_message_text(

File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/messages/edit_message_text.py", line 82, in edit_message_text

r = await self.invoke(

File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke

r = await self.session.invoke(

File "/usr/local/lib/python3.9/dist-packages/pyrogram/session/session.py", line 381, in invoke

return await self.invoke(query, retries - 1, timeout)

File "/usr/local/lib/python3.9/dist-packages/pyrogram/session/session.py", line 361, in invoke

return await self.send(query, timeout=timeout)

File "/usr/local/lib/python3.9/dist-packages/pyrogram/session/session.py", line 331, in send

RPCError.raise_it(result, type(data))

File "/usr/local/lib/python3.9/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it

raise getattr(

pyrogram.errors.exceptions.bad_request_400.MessageNotModified: Telegram says: [400 MESSAGE_NOT_MODIFIED] - The message was not modified because you tried to edit it using the same content (caused by "messages.EditMessage") `
```
